[tool.poetry]
name = "srite-bot"
version = "0.0.0"
description = "SriteBot Discord Bot"
authors = ["HN67"]

[tool.poetry.dependencies]
python = ">=3.8"
"discord.py" = "^1.4"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
